# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

jobs:
 pool:

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

#- script: |
#    npm run test
#  displayName: 'test'

- script: |
    echo "$(Build.BuildNumber)"
  displayName: 'Echo variables'

- task: PowerShell@2
  inputs:
    targetType: inline
    #filePath: # Required when targetType == FilePath
    #arguments: # Optional
    script: '##vso[task.setvariable variable=version](. .\buildfunctions.ps1; addBuildNumber -buildNumber $(Build.BuildNumber))' # Required when targetType == Inline
    #errorActionPreference: 'stop' # Optional. Options: stop, continue, silentlyContinue
    #failOnStderr: false # Optional
    #ignoreLASTEXITCODE: false # Optional
    #pwsh: false # Optional
    #workingDirectory: # Optional

- script: |
    npm install -g vsce
    vsce package
  displayName: 'Package'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'snsb-$(version).vsix'
    targetPath: './snsb-$(version).vsix'