# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

#- script: |
#    npm run test
#  displayName: 'test'

#set add build number to version
- task: PowerShell@2
  inputs:
    targetType: inline
    #filePath: # Required when targetType == FilePath
    #arguments: # Optional
    script: '. .\buildfunctions.ps1; $v = addBuildNumber -buildNumber $(Build.BuildNumber);write-host "##vso[task.setvariable variable=vsix]snsb-$v.vsix"' # Required when targetType == Inline
    #errorActionPreference: 'stop' # Optional. Options: stop, continue, silentlyContinue
    #failOnStderr: false # Optional
    #ignoreLASTEXITCODE: false # Optional
    #pwsh: false # Optional
    #workingDirectory: # Optional

- script: |
    echo "$(Build.BuildNumber)"
    echo "$(vsix)"
  displayName: 'Echo variables'

- script: |
    echo npm install -g vsce
    echo vsce package -o ".\$(vsix)"
  displayName: 'Package'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: "$(vsix)"
    targetPath: "./$(vsix)"